daniel-ac-martin/NotGovUK

.storybook/decorators.tsx, package.json, src/index.js, src/lib/components/anchor/README.md, src/lib/components/anchor/index.spec.ts, src/lib/components/anchor/index.stories.mdx, src/lib/components/anchor/index.tsx, src/lib/components/back-link/index.tsx, src/lib/components/breadcrumbs/index.tsx, src/lib/components/button/anchor.tsx, src/lib/components/footer/index.tsx, src/lib/components/header/index.tsx, src/lib/components/index.js, src/lib/components/index.scss, src/lib/components/page/index.tsx, src/lib/typography/links.scss
With this change our components will need to be wrapped in a router. On the client this would be `BrowserRouter` on the server this would be `StaticRouter`.
=> Add React Router support

package.json, src/lib/components/anchor/index.tsx, src/lib/components/back-link/index.spec.ts, src/lib/components/breadcrumbs/index.spec.ts, src/lib/components/button/index.spec.ts, src/lib/components/footer/index.tsx, src/lib/components/header/index.scss, src/lib/components/header/index.spec.ts, src/lib/components/index.js, src/lib/components/page/index.stories.mdx, src/lib/components/page/index.tsx, src/lib/components/site/README.md, src/lib/components/site/index.spec.ts, src/lib/components/site/index.stories.mdx, src/lib/components/site/index.tsx
Adds the first iteration of the `Site` component. This is at quite an
early stage but it allows us to demonstrate the power of React Router.
=> Add Site component

src/lib/components/form-field/date-input.tsx, src/lib/forms/lib/validators.ts
This will better facilitate leading zeroes.
=> DateInput: Fix: Use text inputs not numbers

README.md
Corrects a few spelling/grammar errors, and adds a stab at the "Why Typescript?" section.
=> Minor content updates

.github/workflows/test.yml, pnpm-lock.yaml
Adds basic CI by adding a GitHub Actions 'workflow' for running the unit
tests. The intention would be to extend this to build packages and
possible store the results as artifacts.
=> Add basic Continuous Integration (GitHub Actions)

.github/workflows/deploy-docs.yml, apps/govuk-docs/package.json, apps/govuk-template/package.json, apps/govuk-template/serverless.yml, pnpm-lock.yaml, skel/app/package.json.hbs
Adds a workflow for deploying the documentation website to Netlify.
Addresses #23.
=> CI: Add workflow for deploying documentation site

LICENSE, apps/govuk-docs/package.json, apps/govuk-template/package.json, components-internal/anchor/package.json, components-internal/simple-table/package.json, components/back-link/package.json, components/form/package.json, components/link/package.json, components/table/package.json, components/tag/package.json, lib-govuk/sass-base/package.json, lib/app-composer/package.json, lib/client-renderer/package.json, lib/component-helpers/package.json, lib/component-test-helpers/package.json, lib/docs-components/package.json, lib/engine/package.json, lib/forms/package.json, lib/restify/package.json, lib/route-utils/package.json, lib/server-renderer/package.json, lib/storybook-preset/package.json, lib/webpack-config/package.json, old-packages/storybook/package.json, package.json, packages/components/package.json
Adds the MIT software license.
=> Add copyright license

apps/govuk-docs/package.json, apps/govuk-template/package.json, components-internal/anchor/package.json, components-internal/simple-table/package.json, components/back-link/package.json, components/form/package.json, components/link/package.json, components/table/package.json, components/tag/package.json, lib-govuk/sass-base/package.json, lib/app-composer/package.json, lib/client-renderer/package.json, lib/component-helpers/package.json, lib/component-test-helpers/package.json, lib/create/package.json, lib/docs-components/package.json, lib/engine/package.json, lib/forms/package.json, lib/plop-pack/package.json, lib/restify/package.json, lib/route-utils/package.json, lib/server-renderer/package.json, lib/storybook-preset/package.json, lib/webpack-config/package.json, package.json, packages/components/package.json
First version with the 'create' package included.
=> Version 0.1.1

lib/create/package.json
=> create: Fix: Add skel/ to the package

lib/create/Makefile
We need to ensure that Make will replace these files with our custom
versions.
=> create: Fix: Remove unwanted files from docs app

lib-govuk/create/.gitignore, lib-govuk/create/Makefile, lib-govuk/create/README.md, lib-govuk/create/bin/create, lib-govuk/create/package.json, lib-govuk/create/plopfile.js, lib-govuk/plop-pack/.gitignore, lib-govuk/plop-pack/README.md, lib-govuk/plop-pack/package.json, lib-govuk/plop-pack/skel/app/package.json.hbs, lib-govuk/plop-pack/skel/app/src/common/app.scss, lib-govuk/plop-pack/skel/app/src/common/error-page.tsx, lib-govuk/plop-pack/skel/app/src/common/loading-page.tsx, lib-govuk/plop-pack/skel/app/src/common/page-wrap.tsx, lib-govuk/plop-pack/skel/app/src/common/pages/index.tsx, lib-govuk/plop-pack/skel/app/src/server/template.tsx, lib-govuk/plop-pack/src/index.js, lib/create/Makefile, lib/create/bin/create, lib/create/package.json, lib/create/plopfile.js, lib/plop-pack/package.json, lib/plop-pack/skel/app/src/common/pages/two.tsx, lib/plop-pack/src/actions/merge.js, lib/plop-pack/src/extend-generator.js, lib/plop-pack/src/index.js, lib/plop-pack/src/run-plop.js, packages/components/.npmignore, packages/components/package.json, pnpm-lock.yaml
So far the generators have been producing unbranded apps and projects. This changes this to provide GovUK-themed versions that build on the basic ones. This should also provide us with a pattern for design-systems to provide their own generators in turn.
=> GovUK-themed generators

README.md, apps/govuk-docs/src/common/page-wrap.tsx, apps/govuk-docs/src/common/pages/contributing.tsx, apps/govuk-docs/src/common/pages/design-decisions.tsx, apps/govuk-docs/src/common/pages/get-started.tsx, apps/govuk-docs/src/common/pages/index.tsx, apps/govuk-docs/src/common/pages/working-on-your-project.tsx, docs/about.md, docs/contributing.md, docs/design-decisions.md, docs/get-started.md, docs/working-on-your-project.md, lib/create/skel/README.md.hbs
Breaks up the README into more digestible chunks as most people won't be
interested in all of it.
Addresses #88.
=> Break up documentation

lib-govuk/create/plopfile.js, lib/create/Makefile, lib/create/plopfile.js, packages/components/src/components/page/index.tsx
These are problems highlighted by working on child projects.
=> Miscellaneous fixes

lib/webpack-config/index.js
This is an attempt at addressing #113.
=> Fix errors on OSX

components-internal/anchor/src/Anchor.tsx
Applies a stricter form of matching when determining if a link is
currently active. In addition to the standard matching, it also checks
that the target query object is represented in the current query.
(Additional properties will NOT prevent matching.)
=> Anchor: Apply stricter matching

.github/workflows/chromatic.yml, .github/workflows/deploy-docs.yml, .github/workflows/test.yml
This contains a fix to work with the current GitHub Actions.
=> CI: Update pnpm-action

tsconfig.json
=> TypeScript: Provide defaults for include & exclude

lib/plop-pack/skel/app/src/server/config.ts, lib/plop-pack/skel/app/src/server/index.ts
Updates the app skeleton in accordance with the govuk-template
application.
=> plop-pack: Update app skeleton

apps/govuk-docs/Dockerfile, apps/govuk-docs/Makefile, apps/govuk-docs/README.md, apps/govuk-template/Dockerfile, apps/govuk-template/Makefile, apps/govuk-template/README.md, lib/plop-pack/skel/app/.dockerignore, lib/plop-pack/skel/app/Dockerfile, lib/plop-pack/skel/app/Makefile.hbs, lib/plop-pack/skel/app/README.md.hbs, lib/plop-pack/src/generators/app.js, pnpm-lock.yaml
Adds support for building the applications as Docker images and deploying them to Kubernetes.
=> Docker support

apps/govuk-template/src/common/pages/search.tsx, lib/forms/package.json, lib/forms/src/completion.ts, lib/forms/src/context.ts, lib/forms/src/hocs.ts, lib/forms/src/index.ts, pnpm-lock.yaml
Also removes the `dataKey` functionality as this was found to be broken.
=> forms: Fix: Prevent infinite loop 

components/form/src/Form.ts, components/form/src/controls.ts, components/form/src/fields.ts, lib/forms/src/hocs.ts, lib/forms/src/index.ts, packages/components/src/forms/controls.ts, packages/components/src/forms/fields.ts, packages/components/src/forms/index.ts
Makes forms more extensible by exporting a new `withForm` HOC.
=> Make forms more extensible

components/tag/package.json, components/tag/spec/Tag.stories.mdx, packages/components/src/typography/paragraphs.scss, pnpm-lock.yaml
Also moves away from using the `text` prop.
=> Tag: Complete documentation

packages/components/package.json, packages/components/src/components/index.ts, pnpm-lock.yaml
Makes the Tabs component available through the meta-package.
=> components: Export the Tabs component

.github/workflows/chromatic.yml, .github/workflows/deploy-docs.yml, .github/workflows/test.yml
Up the pnpm action versions to fix some bit-rot.
=> CI: update pnpm action

apps/govuk-docs/README.md, apps/govuk-template/README.md, lib/component-helpers/README.md, lib/component-test-helpers/README.md, lib/create/skel/project/README.md.hbs, lib/create/skel/prototype/README.md.hbs, lib/docs-components/README.md, lib/forms/README.md, lib/plop-pack/jest.config.js, lib/plop-pack/package.json, lib/plop-pack/skel/app/README.md.hbs, lib/plop-pack/skel/component/README.md.hbs, lib/plop-pack/skel/lib/README.md.hbs, lib/plop-pack/spec/helpers/title.js, lib/plop-pack/src/helpers/title.js, lib/plop-pack/src/index.js, lib/route-utils/README.md, pnpm-lock.yaml
=> Update component skeleton readme

apps/govuk-template/src/server/config.ts, apps/govuk-template/src/server/index.ts, lib/engine/package.json, lib/engine/src/index.ts, lib/engine/src/lib/auth/basic.ts, lib/engine/src/lib/auth/common.ts, lib/engine/src/lib/auth/index.ts, lib/engine/src/lib/auth/passport.ts, lib/plop-pack/skel/app/src/server/config.ts, lib/plop-pack/skel/app/src/server/index.ts, pnpm-lock.yaml
Adds support for private websites which will apply authentication to the entire website including the static assets.
=> Support for private websites

lib/docs-components/src/index.ts
... without any stories in them.
=> docs-components: Allow standalone Previews

lib/webpack-config/package.json, pnpm-lock.yaml
This is to prevent annoying deprecation messages.
=> webpack-config: Pin dart-sass

apps/govuk-docs/aws.serverless.yml, apps/govuk-template/aws.serverless.yml, lib/plop-pack/skel/app/aws.serverless.yml.hbs
This is a follow on from #364.
=> plop-pack: Update Serverless config to new syntax

lib/webpack-config/index.js, lib/webpack-config/package.json, pnpm-lock.yaml
=> webpack-config: Update mini-css-extract-plugin

lib/webpack-config/package.json, pnpm-lock.yaml, tsconfig.webpack.json
=> webpack-config: Update fork-ts-checker-webpack-plugin

apps/govuk-template/src/server/config.ts, apps/govuk-template/src/server/index.ts, lib/engine/src/index.ts, lib/plop-pack/skel/app/src/server/config.ts, lib/plop-pack/skel/app/src/server/index.ts, lib/restify/src/index.ts, lib/restify/src/lib/logger.ts
Allows setting the log-level.
Allows logging to a file rather than std-out.
Partially addresses: #376
=> Provide some logging options

.github/actions/scan-app/action.yml, .github/workflows/deploy-to-heroku.yml, .github/workflows/deploy-to-netlify.yml, .github/workflows/main.yml
=> CI: Add ZAP (Baseline) for DAST scanning 

.github/workflows/codeql-analysis.yml
This is just the stock config initially.
=> CI: Add CodeQL for static analysis

.github/actions/scan-code/action.yml, .github/workflows/codeql-analysis.yml, .github/workflows/main.yml
=> CI: Simplify set-up for static code analysis

lib/restify/src/index.ts, lib/restify/src/middleware/common.ts, lib/restify/src/middleware/content-security-policy.ts, lib/restify/src/middleware/health-check.ts, lib/restify/src/middleware/html-by-default.ts, lib/restify/src/middleware/no-cache-by-default.ts, lib/restify/src/middleware/prevent-clickjacking.ts, lib/restify/src/middleware/prevent-mime-sniffing.ts, lib/server-renderer/package.json, lib/server-renderer/src/HelmetHead.tsx, lib/server-renderer/src/Scripts.tsx, lib/server-renderer/src/html-envelope.ts, lib/server-renderer/src/index.ts, pnpm-lock.yaml
=> Fixes for issues highlighted by ZAP

.github/actions/scan-code/action.yml, .github/actions/test-code/action.yml, .github/actions/update-built-files/action.yml, .github/workflows/main.yml
=> CI: Prepare to commit .jest-results

.npm/version.sh
It should now update all references to the versioned packages.
=> Improve version script

apps/govuk-docs/plopfile.js, apps/govuk-docs/plopfile.mjs, apps/govuk-template/plopfile.js, apps/govuk-template/plopfile.mjs, lib-govuk/plop-pack/src/index.js, lib/app-plop-pack/src/index.js
There was a bug which completely broken the `npm run create` commands within applications.
=> Fix app generator

apps/govuk-template/feat/html.spec.js, lib/app-composer/src/index.ts, lib/engine/src/lib/pages.ts
Failure to do this was breaking HTML pages.
Fixes: #597
=> Update to ESM interface from html-loader

.github/workflows/change-assurance.yml, .github/workflows/deploy.yml
Tries to conserve the limited number of Chromatic snapshots that we have
each month, by enabling [TurboSnap](https://www.chromatic.com/docs/turbosnap).
=> CI: Conserve Chromatic snapshots

.storybook/main.js, apps/govuk-docs/src/common/pages/components.tsx, components-internal/anchor/src/Anchor.tsx, components/pagination/.gitignore, components/pagination/README.md, components/pagination/assets/Pagination.scss, components/pagination/jest.config.js, components/pagination/package.json, components/pagination/spec/Pagination.stories.mdx, components/pagination/spec/Pagination.ts, components/pagination/src/ItemEllipsis.tsx, components/pagination/src/ItemLink.tsx, components/pagination/src/PageList.tsx, components/pagination/src/Pagination.tsx, components/pagination/src/common.ts, components/pagination/tsconfig.json, lib/component-test-helpers/package.json, lib/component-test-helpers/src/index.ts, packages/components/package.json, packages/components/src/components/index.ts, pnpm-lock.yaml, renovate.json
Also improves support for react-testing-library by exporting more functionality.
Partially addresses: #619
=> Add Pagination component

components/checkboxes/spec/Checkboxes.ts, components/checkboxes/src/Checkbox.tsx, components/radios/spec/Radios.stories.mdx, components/radios/spec/Radios.ts, components/radios/src/Radio.tsx, components/radios/src/Radios.tsx
Also adds `aria-expanded` attribute to Checkboxes component and improves unit tests.
Fixes: #654
=> Radios: Fix conditionally revealed content

apps/govuk-docs/src/common/pages/components.tsx, components/error-summary/.gitignore, components/error-summary/README.md, components/error-summary/assets/ErrorSummary.scss, components/error-summary/jest.config.js, components/error-summary/package.json, components/error-summary/spec/ErrorSummary.stories.mdx, components/error-summary/spec/ErrorSummary.ts, components/error-summary/src/ErrorSummary.tsx, components/error-summary/tsconfig.json, packages/components/package.json, packages/components/src/components/index.ts, pnpm-lock.yaml
=> Add ErrorSummary component

apps/govuk-docs/src/common/pages/components.tsx, components-internal/anchor-list/src/AnchorList.tsx, components/summary-card/.gitignore, components/summary-card/README.md, components/summary-card/assets/SummaryCard.scss, components/summary-card/jest.config.js, components/summary-card/package.json, components/summary-card/spec/SummaryCard.stories.mdx, components/summary-card/spec/SummaryCard.ts, components/summary-card/src/SummaryCard.tsx, components/summary-card/tsconfig.json, lib/plop-pack/skel/component/spec/Component.ts.hbs, packages/components/package.json, packages/components/src/components/index.ts, pnpm-lock.yaml
This will be used in conjunction with the upcoming SummaryList component.
=> Add SummaryCard component

.github/actions/setup/action.yml, .github/workflows/change-assurance.yml, components-internal/anchor/package.json, pnpm-lock.yaml
**BREAKING:** Drops support for Node.js v14.
=> CI: Update PNPM

lib/engine/package.json, pnpm-lock.yaml
We no longer use client-sessions.
=> engine: Remove defunct dependency

apps/govuk-docs/package.json, apps/govuk-template/package.json, components/page/src/GovUKPage.tsx, components/page/src/NotGovUKPage.tsx, components/page/src/Page.tsx, lib/app-composer/src/index.ts, lib/component-test-helpers/src/index.ts, lib/server-renderer/package.json, package.json, pnpm-lock.yaml
Presumably this is a breaking change as it is a major version bump on a context providing package.
=> BREAKING: Update react-helmet-async to v2

lib/webpack-config/package.json, pnpm-lock.yaml
Switches from sass to sass-embedded, which is a drop-in replacement that
should be faster.
=> webpack-config: Switch to sass-embedded

.github/actions/setup/action.yml, .github/actions/test-code/action.yml, .github/workflows/change-assurance.yml, .github/workflows/deploy-to-heroku.yml, .github/workflows/deploy-to-netlify.yml, .github/workflows/deploy.yml, .github/workflows/publish.yml, .github/workflows/static-security-analysis.yml, .github/workflows/update-built-files.yml
CI: Test on Node.js v22 instead of v16
BREAKING: Drop support for Node.js v16
=> BREAKING: Drop support for Node.js v16

.github/actions/setup/action.yml, .github/workflows/change-assurance.yml, .github/workflows/deploy-to-heroku.yml, .github/workflows/deploy-to-netlify.yml, .github/workflows/deploy.yml, .github/workflows/publish.yml, .github/workflows/static-security-analysis.yml, .github/workflows/update-built-files.yml, apps/govuk-docs/aws.serverless.yml, apps/govuk-template/aws.serverless.yml, apps/next-example/package.json, lib/engine/package.json, lib/plop-pack/skel/app/Dockerfile, lib/plop-pack/skel/app/aws.serverless.yml.hbs, lib/server-renderer/package.json, pnpm-lock.yaml
=> Update Node.js to v22

.github/actions/setup/action.yml, .gitignore
Also ignores a MacOS temp-file.
=> CI: Set the locale

.storybook/main.js, .zap/rules.tsv, lib/restify/src/index.ts, lib/restify/src/middleware/private-by-default.ts
This should add some security. We need to be careful that it doesn't
break anything though.
Also, adds missing stories to Storybook.
=> restify: Add Cross-Origin-Resource-Policy header

components/navigation-menu/spec/NavigationMenu.stories.mdx, components/service-navigation/spec/ServiceNavigation.stories.mdx, lib/router/spec/is-active.ts, lib/router/src/is-active.ts
This will in turn fix a bug in the ServiceNavigation and NavigationMenu components.
=> router: Correct inexact matching of isActive()
