daniel-ac-martin/NotGovUK

lib/docs-components/package.json
lib/docs-components/src/ReactPreview.tsx
pnpm-lock.yaml

Improves code formatting by switching from 'js-beautify' to 'prettier'
which has better support for JSX as well as allowing one to optimise for
line width. (Which allows us to reduce horizontal scrolling.)
Improves code highlighting for React by switching from Highlight.js to
PrismJS which seems to have better support for JSX. It might be possible
to improve the highlighting even further by switching from PrismJS's
`javascript` mode on to something more specialised.
Addresses: #33

Improve code snippets

---

lib/docs-components/package.json
lib/docs-components/src/ReactPreview.scss
lib/docs-components/src/ReactPreview.tsx
pnpm-lock.yaml

- Switches to a 'GitHub' theme for PrismSJ in order to improve constrast. (Probably addresses #35.)
- Applies class to `<code>` blocks in accordance with PrismJS
documentation.
- Adds custom styling to prevent the theme from taking too much control.
- Reduces font-size of code snippet to improve aesthetics and to allow
more code to be shown. (Tweaks line length accordingly.)

Further improve code snippets

---

components/form/spec/Form.stories.mdx

Adds a `prettyName` prop to the `fullName` field on the `Form` stories
as the error messages had become ugly after the move from `name="name"`
to `name="fullName"`.
This should make for a nicer demo of the forms functionality.

Form: Better error messages with prettyName

---

lib/webpack-config/index.js
lib/webpack-config/package.json
pnpm-lock.yaml

It looks like we don't need style-loader even for HMR.
(In the apps HMR works just fine without it. I've not tested in
Storybook but I'd be surprised if that was any different.)

webpack-config: Simplify pipeline for CSS

---

lib/docs-components/package.json
lib/docs-components/src/ReactPreview.tsx
pnpm-lock.yaml

Switches Highlight.js for PrismJS when applying syntax highlighting to
HTML. This simplifies the code bringing it into alignment with React. It
also means that visually there is more symmetry between the two.
It does come at the cost of reduced contrast in the colours. - We may
want to re-create the old colour scheme with PrismJS.

docs-components: Use PrismJS for all highlighting

---

lib/docs-components/src/ReactPreview.tsx
lib/docs-components/src/index.ts
styles/forms.stories.mdx

There was a bug on the typography page that was crashing the site. Specifically, we were not wrapping multiple elements in a Fragment, which is something that Babel demands.
In the long run, it might be nice to remove the Fragment afterwards although this might prove quite complicated to do.

Fix typography page

---

lib/create/bin/create
lib/create/package.json

Sets ap a shebang line and renames to remove the `.js` file extension.

Fix create package for npm init

---

lib/create/plopfile.js
lib/create/skel/.gitignore
lib/create/skel/gitignore
lib/create/skel/skel/app/.gitignore
lib/create/skel/skel/app/gitignore
lib/create/skel/skel/component/.gitignore
lib/create/skel/skel/component/gitignore
lib/create/skel/skel/lib/.gitignore
lib/create/skel/skel/lib/gitignore

`.gitignore` files have special significance so we need to rename it if
we want to use it simply for content.

create: Fix: Rename gitignore file

---

lib/plop-pack/skel/component/gitignore
lib/plop-pack/src/generators/app.js
lib/plop-pack/src/generators/component.js
lib/plop-pack/src/generators/lib.js

Renames `.gitignore` files to `gitignore` as NPM refuses to package
them.

plop-pack: Fix: Avoid .gitignore

---

.github/workflows/test.yml

There's no need to run the build on different versions on Node.js.

CI: Break up Test workflow

---

lib-govuk/plop-pack/src/index.js
pnpm-lock.yaml

This is a workaround due to a bug in node-plop. It can be reverted if
and when https://github.com/plopjs/node-plop/pull/180 is merged.

plop-pack: Fix: Rely on Node's module resolution

---

.github/workflows/chromatic.yml

The chromatic tool seems to suggest setting this flag in CI in order to
speed up the job. It sounds like the remaining work is done on the
Chromatic servers and so there's no point in repeating it here.

CI: Speed up push to Chromatic

---

lib-govuk/plop-pack/src/index.js

This is another workaround for the bug in node-plop. Like the other one,
it can be reverted if and when
https://github.com/plopjs/node-plop/pull/180 is merged.

plop-pack: Fix: Second workaround

---

lib-govuk/create/Makefile
lib/create/Makefile

In the long run we should probably use handlebars to customise the markdown that we install.

Update project initialisers to include docs

---

lib/engine/src/lib/webpack.ts
lib/webpack-config/index.js
lib/webpack-config/package.json
pnpm-lock.yaml

Improves the webpack logging by add progress information when bundling and reducing the output in dev-mode so that the user can see what is going on.
Addresses #27.

Improve Webpack logging

---

lib/create/Makefile

This fixes a bug in which the prototypes didn't type-check due to the
lack of a reference to webpack-env.
Addresses: #134

create: Combine tsconfigs for prototypes

---

apps/govuk-docs/src/server/template.tsx
apps/govuk-template/package.json
apps/govuk-template/src/common/pages/graphql-test.tsx
apps/govuk-template/src/common/pages/two.tsx
apps/govuk-template/src/server/index.ts
apps/govuk-template/src/server/template.tsx
lib-govuk/plop-pack/skel/app/src/server/template.tsx
lib/app-composer/package.json
lib/app-composer/src/index.ts
lib/client-renderer/src/index.ts
lib/engine/package.json
lib/engine/src/index.ts
lib/engine/src/lib/pages.ts
lib/plop-pack/skel/app/src/server/template.tsx
lib/restify/src/index.ts
lib/restify/src/lib/router.ts
lib/server-renderer/package.json
lib/server-renderer/src/index.ts
package.json
pnpm-lock.yaml

Add isomorphic GraphQL support as a convenient way to populate components with data from the server.
Begins to address #125.

Add GraphQL support via Apollo Client

---

jest.config.base.js
tsconfig.nodejs.json

This will prevent a huge memory leak at the expense of type checking in
our tests. Once there is a better fix we should consider reverting this.
See: https://github.com/kulshekhar/ts-jest/issues/1967
See: https://kulshekhar.github.io/ts-jest/user/config/isolatedModules
Addresses: #156

Temp-fix: Use isolatedModules in ts-jest

---

components/footer/assets/Footer.scss

We cannot rely on the dependency being installed in an exact location on
the file-system. Instead, we should us the special `~` syntax to do the
module resolution for us.
(Notably, PNPM will _not_ install the dependency where we were
expecting and so the components was broken for our consumers.)

Footer: Fix: Reference dependency correctly

---

lib/app-composer/src/index.ts
lib/server-renderer/src/index.ts

Without this, the resolvers won't be able to use the token to make
upstream requests.

app-composer: Supply accessToken to SchemaLink

---

lib/engine/src/lib/auth/oidc.ts

The cookie is too big so let's fix that by removing the refresh token
which we do not yet use.
We will later need to add support for the token and so will need to
support larger sessions, probably by splitting the cookie.

engine: Fix: Remove refresh token for now

---

Makefile

It should now be possible to publish using the following command:
```shell
make publish version='0.1.34'
```
Note that you should only do this on a completely clean checkout of the
HEAD of the `master` branch.
You should also ensure that your dependencies are up to date by running
`pnpm i`.

Add publish script to Makefile

---

apps/govuk-docs/src/common/page-loader.ts
apps/govuk-template/src/common/page-loader.ts
components/page/spec/Page.stories.mdx
lib/app-composer/src/index.ts
lib/engine/src/lib/pages.ts
lib/plop-pack/skel/app/src/common/page-loader.ts

Webpack's `require.context` allows the user to set a mode. When it is
set to `sync` (the default) the module will NOT be wrapped in a promise
as it would be in `lazy` mode and some other modes.
As it is the default mode and as some users might want to set this we
should support it. To do so, we check that whether we have a promise. If
we do, we wrap the project in `lazy` as usual, otherwise there is no
need for the wrap and we can consume the component immediately.
This is useful as, in most cases, the extra chunks produced are so small
as to be not worth bothering with. i.e. Let's just combine them into the
main bundle.
Also, by avoid lazy loading we can avoid the need to flash up the
loading page which I am worried might be an accessibility problem.

Load pages in sync mode

---

apps/govuk-docs/src/common/pages/components.tsx
components/aside/spec/Aside.stories.mdx
components/back-link/spec/BackLink.stories.mdx
components/breadcrumbs/spec/Breadcrumbs.stories.mdx
components/details/spec/Details.stories.mdx
components/footer/spec/Footer.stories.mdx
components/form/spec/Form.stories.mdx
components/header/spec/Header.stories.mdx
components/inset-text/spec/InsetText.stories.mdx
components/link/spec/Link.stories.mdx
components/page/spec/Page.stories.mdx
components/panel/spec/Panel.stories.mdx
components/phase-banner/spec/PhaseBanner.stories.mdx
components/skip-link/spec/SkipLink.stories.mdx
components/table/spec/Table.stories.mdx
components/tag/spec/Tag.stories.mdx
components/warning-text/spec/WarningText.stories.mdx
components/width-container/spec/WidthContainer.stories.mdx
lib/docs-components/src/DocsPage.tsx
lib/plop-pack/skel/component/spec/Component.stories.mdx.hbs

Adds custom titles to the component pages for accessibility (and correctness).
Also provides OpenGraph meta-data which should help when the pages are shared via things like Slack.

Titles on component pages

---

apps/govuk-template/package.json
apps/govuk-template/src/server/config.ts
lib/plop-pack/skel/app/package.json.hbs

This will allow Heroku to tell us which port to listen on as well as to
automatically build the application and to use a supported version of
Node.js.

Add Heroku support to the applications

---

lib/server-renderer/src/index.ts

The HTML pages were being placed in the hydration data and so were not
subject to hot-loading. To fix this, we explicitly filter out the
`Component` property rather than relying on `JSON.stringify()` to do it
for us.

server-renderer: Fix HTML hot-loading

---

components/aside/package.json
components/back-link/package.json
components/breadcrumbs/package.json
components/details/package.json
components/footer/package.json
components/header/package.json
components/inset-text/package.json
components/link/package.json
components/navigation-menu/package.json
components/page/package.json
components/panel/package.json
components/phase-banner/package.json
components/skip-link/package.json
components/table/package.json
components/tabs/package.json
components/tag/package.json
components/warning-text/package.json
components/width-container/package.json
lib-govuk/sass-base/package.json
packages/components/package.json
pnpm-lock.yaml

It is neceassary to pin the version to avoid a conflict with the most
recent version.

Update govuk-frontend and pin version

---

package.json
pnpm-lock.yaml

Now that we are pinning versions, this should not be necessary and may
be confusing or cause problems.

Remove most package overrides

---

components/button-group/package.json
components/button/package.json
components/checkboxes/package.json
components/cookie-banner/package.json
components/date-input/package.json
components/error-message/package.json
components/fieldset/package.json
components/form-group/package.json
components/hint/package.json
components/input/package.json
components/label/package.json
components/radios/package.json
components/select/package.json
components/textarea/package.json
components/visually-hidden/package.json
package.json
pnpm-lock.yaml

Sets the pinned version of govuk-frontend to always be v3.11.0 and removes the PNPM override.

Harmonise govuk-frontend versions

---

lib/webpack-config/index.js
lib/webpack-config/package.json
pnpm-lock.yaml

This is required for the latest version of openid-client.

webpack-config: Add support for private methods

---

apps/govuk-docs/package.json
apps/govuk-template/package.json
lib/plop-pack/skel/app/package.json.hbs

We don't support this due to our current use of fibres.

plop-pack: Avoid running on Node.js v16

---

components/footer/assets/Footer.scss
lib-govuk/sass-base/src/index.scss

This should allow webpack to find the files and eliminate the need for
overrides.

sass-base: Set the asset path to be relative

---

lib/engine/src/index.ts

This should avoid a breaking change for the time-being.

engine: Make readiness function optional

---

components/header/src/CrownLogo.tsx
components/page/src/GovUKPage.tsx
components/page/src/NotGovUKPage.tsx
lib/webpack-config/index.js
lib/webpack-config/package.json
pnpm-lock.yaml

Replaces `file-loader` with webpack v5's asset modules.
**BREAKING:** When `require()`ing in assets, one should no longer use the `.default` property. (Just use the object itself.)

webpack-config: Replace file-loader

---

lib/asset-proxy/package.json
lib/asset-proxy/src/index.ts
lib/asset-proxy/src/lib/webpack.ts
lib/express-adapter/package.json
lib/express-adapter/src/index.ts
pnpm-lock.yaml

Enhances the 'express-adapter' package so that it can also be used by the asset-proxy when consuming the webpack middleware.

Enhance express-adapter and re-use

---

apps/govuk-docs/package.json
apps/govuk-docs/src/server/config.ts
apps/govuk-docs/src/server/httpd.ts
apps/govuk-template/package.json
apps/govuk-template/src/server/config.ts
apps/govuk-template/src/server/httpd.ts
lib/consent-cookies/.gitignore
lib/consent-cookies/README.md
lib/consent-cookies/jest.config.js
lib/consent-cookies/package.json
lib/consent-cookies/src/common.ts
lib/consent-cookies/src/index.ts
lib/consent-cookies/src/sessions.ts
lib/consent-cookies/tsconfig.json
lib/engine/package.json
lib/engine/src/index.ts
lib/engine/src/lib/auth/basic.ts
lib/engine/src/lib/auth/common.ts
lib/engine/src/lib/auth/index.ts
lib/engine/src/lib/auth/oidc.ts
lib/engine/src/lib/auth/passport.ts
lib/engine/src/lib/config-helpers.ts
lib/plop-pack/skel/app/package.json.hbs
lib/plop-pack/skel/app/src/server/config.ts
lib/plop-pack/skel/app/src/server/httpd.ts
pnpm-lock.yaml

Under European legislation (still valid in the UK) we should require users to opt-in to optional cookies before setting them on their device. This provides the underlying, server-side support for tracking which cookies they have consented to and will lay the groundwork for providing UI elements for this 'out of the box'.
**BREAKING:** The `auth.sessionSecret` config option has been replaced with
`cookies.secret`. Users will need to update their calling code to accommodate.

Add underlying support for cookies with consent

---

.github/actions/scan-code/action.yml
.github/workflows/analysis.yml
.github/workflows/change-assurance.yml
.github/workflows/deploy-to-heroku.yml
.github/workflows/deploy-to-netlify.yml
.github/workflows/deploy.yml
.github/workflows/update-built-files.yml
lib-govuk/create/Makefile
lib/app-plop-pack/skel/.github/workflows/deploy.deploy.yml.hbs
lib/app-plop-pack/src/index.js
lib/create/Makefile
lib/create/plopfile.js
lib/create/skel/prototype/.github/workflows/change-assurance.yml
lib/create/skel/prototype/.github/workflows/deploy.yml
lib/plop-pack/src/generators/app.js

Not splitting Main leads to duplication of work between pull requests
and pushes. This should also allow us to better support external PRs.

CI: Split up Main workflow

---

lib-govuk/create/plopfile.js
lib/create/plopfile.js

extendGenerator is now an async function so we must await the result.

create: Fix call to extendGenerator

---

.github/actions/scan-code/action.yml
.github/actions/scan-dependencies/action.yml
.github/workflows/change-assurance.yml
.github/workflows/static-security-analysis.yml
.github/workflows/update-built-files.yml

SCA (dependency scanning) is slow and has little value in change assurance. This splits it out to be run only as a regular scan against the code-base.
SAST (CodeQL) is moved into the standard change assurance workflow.

CI: Split SCA from SAST

---

components/form-group/src/FormGroup.tsx
components/text-input/src/TextInput.tsx
components/textarea/src/Textarea.tsx
reports/.sastscan.baseline

- Update **TextInput**, **TextArea** and **FormGroup** (which automatically fixes **DateInput**, **Radios** and **Checkboxes**) components
- In above components the internal `aria-describedby` attribute only references the **hint** element by ID when it actually exists. This allows hint to be truly optional eliminating HTML validation and accessibility issues currently happening.
- Add logic in the same components to reference the error message by ID for `aria-describedby` when error message exists. When error message and hint both are present, referencing error takes priority.
I haven't added any new tests, but manually testing the components in Storybook, I can verify that  both issues raised in https://github.com/daniel-ac-martin/NotGovUK/issues/656 are fixed and the components work as …

Improve hint and error ARIA logic in Form controls

---

lib/asset-proxy/src/index.ts
lib/express-adapter/src/index.ts
renovate.json

It seems that the local dev environment has been broken since the last major Restify update (#684).
New versions of Restify now give special treatment to async middleware.
(Even refusing async functions that take a `next` parameter.) Therefore,
we must adapt them before passing them to Restify.

Fix local dev environment

---

.github/actions/setup/action.yml
.github/workflows/change-assurance.yml
.github/workflows/deploy-to-heroku.yml
.github/workflows/deploy-to-netlify.yml
.github/workflows/deploy.yml
.github/workflows/publish.yml
.github/workflows/static-security-analysis.yml
.github/workflows/update-built-files.yml
apps/govuk-docs/aws.serverless.yml
apps/govuk-docs/src/server/config.ts
apps/govuk-template/aws.serverless.yml
apps/govuk-template/src/server/config.ts
lib/plop-pack/skel/app/Dockerfile
lib/plop-pack/skel/app/aws.serverless.yml.hbs
lib/plop-pack/skel/app/src/server/config.ts

Completes the update to Node.js v18.

Update Node.js to v18

---

components/checkboxes/src/Checkbox.tsx
components/radios/src/Radio.tsx

Only sets the `aria-expanded` attribute when we have a conditional to display.

Checkboxes,Radios: Only set aria with a conditional

---

components/text-input/package.json
components/text-input/src/TextInput.tsx
pnpm-lock.yaml

Without this, the error styling is not applied to the input.

TextInput: Fix: Pass on class props

---

renovate.json

- **Require minimum age before updating**
This should give us some protection from malicious packages.
- **Only run once a week**
This should help to make Renovate a bit less noisy.

Renovate: Update config

---

apps/govuk-docs/src/common/pages/components.tsx
components/notification-banner/.gitignore
components/notification-banner/README.md
components/notification-banner/assets/NotificationBanner.scss
components/notification-banner/jest.config.js
components/notification-banner/package.json
components/notification-banner/spec/NotificationBanner.stories.mdx
components/notification-banner/spec/NotificationBanner.ts
components/notification-banner/src/NotificationBanner.tsx
components/notification-banner/tsconfig.json
components/summary-card/src/SummaryCard.tsx
components/summary-list/src/SummaryListContainer.tsx
components/summary-list/src/SummaryListItem.tsx
packages/components/package.json
packages/components/src/components/index.ts
pnpm-lock.yaml

Add NotificationBanner component

---

lib/restify/src/index.ts

We now can have pre middleware that requires a body parser so we need to elevate these.
This fixes a big in which POST requests would fail when using OpenID Connect in privacy mode.

restify: Elevate request parsers to pre middleware

---

lib/consent-cookies/src/index.ts
lib/engine/src/lib/auth/oidc.ts

This lets us fit more data into the cookies.

Use base64 encoding in cookies

---

apps/govuk-template/src/server/config.ts
apps/govuk-template/src/server/httpd.ts
lib/engine/src/index.ts
lib/plop-pack/skel/app/src/server/config.ts
lib/plop-pack/skel/app/src/server/httpd.ts
lib/restify/src/index.ts
lib/restify/src/middleware/content-security-policy.ts
lib/restify/src/middleware/prevent-clickjacking.ts

Allows the user to provide a `frameAncestors` option to the engine, which follows the [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) format. An equivalent environment variable has also been created.
Only allow us to put our pages in frames:
```shell
FRAME_ANCESTORS="'self'"
```
**Note:** Pay attention to the single quotes!
Also allow example.com and its subdomains:
```shell
FRAME_ANCESTORS="'self',*example.com"
```
Allow all frames (not advised):
```shell
FRAME_ANCESTORS="*"
```
To disallow frames (default):
```shell
FRAME_ANCESTORS="'none'"
```
We disallow frames by default in order to prevent click jacking.
Partially addresses: #950

Allow frame ancestors

---

apps/govuk-docs/package.json
apps/govuk-template/package.json
cypress.config.mjs
lib/plop-pack/skel/app/test.Dockerfile
package.json
pnpm-lock.yaml

This requires installing process in the base of the repo. (Due to
incompatibility with PNPM?)
It also requires us to disable testIsolation, as we do not yet support
that.
This should fix the issue with Firefox-based tests being broken.

CI: Update cypress to v13

---

apps/govuk-docs/src/common/page-loader.ts
apps/govuk-template/feat/md.spec.js
apps/govuk-template/feat/mdx.spec.js
apps/govuk-template/src/common/page-loader.ts
apps/govuk-template/src/common/pages/md.md
apps/govuk-template/src/common/pages/mdx.mdx
lib/engine/src/lib/pages.ts
lib/plop-pack/skel/app/src/common/page-loader.ts

Enables support (in engine and the app generator) for Markdown pages.
This means that Markdown can be placed in the pages directory of an app
rather than imported into a TSX page.

First class support for Markdown and MDX

---

lib/app-composer/src/index.ts
lib/restify/src/middleware/content-security-policy.ts
lib/restify/src/middleware/permissions-policy.ts
lib/server-renderer/src/HelmetHead.tsx
lib/server-renderer/src/html-envelope.ts

These warnings will become errors in React v18.
We do two things:
1. We remove whitespace between the tags that we are hydrating on
2. We remove suspense from the server render for now, as we cannot use
it on the client, and hydration requires an identical tree
Also fixes some bugs in the CSP and the Permissions-Policy.

Fix hydration warnings

---

apps/next-example/next.config.mjs
lib/router/package.json
lib/router/src/index.ts
lib/router/src/next.ts

Provides a new `next` export to the router package. i.e: `@not-govuk/router/next`
The use of the original export is now deprecated and will raise warnings. In a future version the old method will no longer work.

Align Next.js interface with Remix interface

---

.github/actions/update-built-files/action.yml
.github/workflows/update-built-files.yml
.gitignore

If we .gitignore this file, we should be able to manage it exclusively
in CI, which is probably easier and more secure.

Manage package lock-file in CI

---

apps/govuk-docs/src/common/stories.ts
components/navigation-menu/spec/NavigationMenu.stories.mdx
components/search-box/assets/SearchBox.scss
components/search-box/spec/SearchBox.stories.mdx
components/service-navigation/.gitignore
components/service-navigation/README.md
components/service-navigation/assets/ServiceNavigation.scss
components/service-navigation/jest.config.js
components/service-navigation/package.json
components/service-navigation/spec/ServiceNavigation.stories.mdx
components/service-navigation/spec/ServiceNavigation.ts
components/service-navigation/src/ServiceNavigation.tsx
components/service-navigation/tsconfig.json
lib-govuk/simple-components/package.json
lib-govuk/simple-components/src/index.ts
lib/client-renderer/src/index.ts
lib/component-test-helpers/src/index.ts
lib/server-renderer/src/index.ts

Adds the new ServiceNavigation component from GDS.
Also:
- Deprecates the horizontal style for NavigationMenu (users should probably use the new ServiceNavigation component)
- Fixes some styling bugs on the SearchBox component
- Adds a 'secondary' to the SearchBox component for more subtle buttons
- Opts into some v7 react-router features that don't appear harmful (potentially BREAKING, but unlikely)

Add ServiceNavigation component

---

components/date-input/spec/DateInput.ts
components/date-input/src/DateInput.tsx

The `DateInput` component types for  the `value` and `defaultValue` prop expect to be both the default type for the `InputHTMLAttributes<HTMLInputElement>,` e.g. `string | string[] | undefined` but _ALSO_ a `DateInputValue` which expects an object of. `{ day: string, month: string, year: string }`
It is not possible for the value to be both a string and an object!
This fix allows the `value` and `defaultValue` to be set as a `DateInputValue` only by using `Omit` to exclude the default types from the `HTMLInputElement` type, in the same way that `label` was omitted.
This change allows the DateInput component to work properly with `react-hook-form` which passes the `value` into the component via the `register` function and `onChange` functions.

DateInput: Fix type of value props

---

components-internal/simple-table/src/SimpleTable.tsx
components/table/spec/Table.stories.mdx
components/table/src/Table.tsx

Allows custom elements to be provided as captions for Table. Also sets the `--m` styling by default.
Fixes: #1364

More flexibity in captions for tables

---

apps/next-example/src/app/layout.tsx
apps/next-example/src/app/three/page.tsx
apps/next-example/src/components/AddBodyClass.tsx
apps/remix-example/app/root.tsx
apps/remix-example/app/routes/three.tsx
docs/components.md

Sets the `js-enabled` class on the `<body>` element when client-side JavaScript executes. This is in both the Next.js and Remix examples.
closes: #1551

Set body class in examples
